
#### General Configuration Parameters ####
SAVE_SCHEDULE: range(0,1000001, 20000)

NUMBER_OF_LOADING_WORKERS: 12   # Number of threads used in the data loader

#### Input related parameters ####
SENSORS:
  rgb: (3, 88, 200)
MEASUREMENTS:
  targets: (31)

BATCH_SIZE: 120
NUMBER_ITERATIONS: 1000000
TARGETS: ['steer', 'throttle', 'brake']
INPUTS: ['speed_module']
INTENTIONS: ['pedestrian', 'traffic_lights', 'vehicle']
NUMBER_FRAMES_FUSION: 1
NUMBER_IMAGES_SEQUENCE: 1
SEQUENCE_STRIDE: 1
AUGMENT_LATERAL_STEERINGS: 6  # Depending on this value there is a constant multiplying lateral steers
SPEED_FACTOR: 12.0
TRAIN_DATASET_NAME: 'CARLA100'
AUGMENTATION: None
DATA_USED: 'all'
USE_NOISE_DATA: True
NUMBER_OF_HOURS: 50

#### Testing Related Parameters ####
TEST_SCHEDULE: [100000, 300000, 500000, 700000, 1000000]  # The frequency the model is actually tested.



#### Network Related Parameters ####



MODEL_TYPE: 'coil-icra'
MODEL_CONFIGURATION:  # good place to check integrity. All sizes should match
  perception:
    res:
      name: 'resnet34'
      num_classes: 512

  measurements:
    fc:
      neurons: [128, 128]
      dropouts: [0.0, 0.0]
  join:
    fc:
      neurons: [512]
      dropouts: [0.0]
  speed_branch:
    fc:
      neurons: [256, 256]
      dropouts: [0.0, 0.5]
  branches:
    number_of_branches: 4
    fc:
      neurons: [256, 256]
      dropouts: [0.0, 0.5]



LEARNING_RATE: 0.0002  # First
LEARNING_RATE_DECAY_INTERVAL: 100000
LEARNING_RATE_DECAY_LEVEL: 0.5

#TODO check how to use this part
BRANCH_LOSS_WEIGHT: [0.95, 0.95, 0.95, 0.95, 0.05]
LOSS_FUNCTION: 'L1_attention'
USED_LAYERS_ATT: [1]


# The variable weigths used when using the loss function
VARIABLE_WEIGHT:
  Steer: 0.5
  Gas: 0.45
  Brake: 0.05
  L1: 0.0
  L2: 0.0
  AVGP_Kernel_Size: 3  # The kernel size used for average pooling.

#### Simulation Related Parameters ####
IMAGE_CUT: [90, 485]  # How you should cut the input image that is received from the server
USE_ORACLE: False
USE_FULL_ORACLE: False




